-- ============================================================
-- V1__Create_initial_schema.sql
-- Initial database schema for Author Book Management System
-- Tables: users, user_roles, authors, books
-- Column lengths match Hibernate 6 generated DDL exactly.
-- ============================================================

-- Users table (stores authentication credentials)
CREATE TABLE IF NOT EXISTS users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50)  NOT NULL,
    password VARCHAR(255) NOT NULL,
    enabled  BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_users_username UNIQUE (username)
);

-- User roles join table
-- role is VARCHAR(255) to match Hibernate's default (no @Column(length=) on Set<String>)
CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT       NOT NULL,
    role    VARCHAR(255) NOT NULL,
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Authors table
CREATE TABLE IF NOT EXISTS authors (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50)  NOT NULL,
    last_name  VARCHAR(50)  NOT NULL,
    email      VARCHAR(255) NOT NULL,
    biography  VARCHAR(500),
    birth_year INT,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT uq_authors_email UNIQUE (email),
    CONSTRAINT uq_authors_name  UNIQUE (first_name, last_name)
);

-- Books table
-- isbn and genre are VARCHAR(255) to match Hibernate's default
-- (no @Column(length=) on those fields in the Book entity)
CREATE TABLE IF NOT EXISTS books (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(200)   NOT NULL,
    isbn             VARCHAR(255)   NOT NULL,
    publication_year INT            NOT NULL,
    genre            VARCHAR(255)   NOT NULL,
    price            DECIMAL(8, 2),
    available_copies INT            DEFAULT 0,
    description      VARCHAR(1000),
    author_id        BIGINT         NOT NULL,
    created_at       TIMESTAMP(6),
    updated_at       TIMESTAMP(6),
    CONSTRAINT uq_books_isbn   UNIQUE (isbn),
    CONSTRAINT fk_books_author FOREIGN KEY (author_id) REFERENCES authors (id) ON DELETE CASCADE
);
